export const customTheme = {
    "light": {
        "--hsl-primary": "337, 72%, 41%",
        "--color-primary": "hsla(var(--hsl-primary), 1)",
        "--hsl-on-primary": "0, 0%, 100%",
        "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
        "--hsl-primary-container": "349, 100%, 93%",
        "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
        "--hsl-on-primary-container": "336, 100%, 12%",
        "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
        "--hsl-info": "346, 15%, 40%",
        "--color-info": "hsla(var(--hsl-info), 1)",
        "--hsl-on-info": "0, 0%, 100%",
        "--color-on-info": "hsla(var(--hsl-on-info), 1)",
        "--hsl-info-container": "349, 100%, 93%",
        "--color-info-container": "hsla(var(--hsl-info-container), 1)",
        "--hsl-on-info-container": "346, 34%, 13%",
        "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
        "--hsl-warning": "30, 41%, 34%",
        "--color-warning": "hsla(var(--hsl-warning), 1)",
        "--hsl-on-warning": "0, 0%, 100%",
        "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
        "--hsl-warning-container": "28, 100%, 87%",
        "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
        "--hsl-on-warning-container": "30, 100%, 9%",
        "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
        "--hsl-danger": "0, 75%, 42%",
        "--color-danger": "hsla(var(--hsl-danger), 1)",
        "--hsl-on-danger": "0, 0%, 100%",
        "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
        "--hsl-danger-container": "6, 100%, 92%",
        "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
        "--hsl-on-danger-container": "358, 100%, 13%",
        "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
        "--hsl-body": "300, 100%, 99%",
        "--color-body": "hsla(var(--hsl-body), 1)",
        "--hsl-text": "350, 10%, 11%",
        "--color-text": "hsla(var(--hsl-text), 1)",
        "--hsl-on-surface-variant": "347, 9%, 29%",
        "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
        "--hsl-outline": "349, 7%, 48%",
        "--color-outline": "hsla(var(--hsl-outline), 1)",
        "--hsl-inverse-surface": "350, 6%, 20%",
        "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)",
        "--chip-round-radius": "8px",
        "--field-decorator-line-border-radius": "50px",
        "--ripple-color": "hsla(var(--hsl-primary), 1)",
        "--hsl-profile-background": "0, 0%, 91%",
        "--color-profile-background": "hsla(var(--hsl-profile-background), 1)",
        "--cell-padding": "0",
        "--card-background": "hsla(var(--hsl-body), 1)",
        "--bottom-navigation-background-color": "hsla(var(--hsl-body), 1)",
        "--tabs-indicator-inner-size": "50px",
        "--cell-font-size": "16px",
        "--cell-font-right": "100",
        "--result-background": "var(--color-body)",
        "--back-top-button-size": "60px",
        "--tabs-background": "var(--color-body)",
},
    "dark": {
    "--hsl-primary": "346, 100%, 85%",
        "--color-primary": "hsla(var(--hsl-primary), 1)",
        "--hsl-on-primary": "334, 100%, 20%",
        "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
        "--hsl-primary-container": "333, 100%, 28%",
        "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
        "--hsl-on-primary-container": "349, 100%, 93%",
        "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
        "--hsl-info": "349, 42%, 82%",
        "--color-info": "hsla(var(--hsl-info), 1)",
        "--hsl-on-info": "346, 24%, 21%",
        "--color-on-info": "hsla(var(--hsl-on-info), 1)",
        "--hsl-info-container": "347, 18%, 30%",
        "--color-info-container": "hsla(var(--hsl-info-container), 1)",
        "--hsl-on-info-container": "349, 100%, 93%",
        "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
        "--hsl-warning": "29, 72%, 75%",
        "--color-warning": "hsla(var(--hsl-warning), 1)",
        "--hsl-on-warning": "32, 77%, 15%",
        "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
        "--hsl-warning-container": "31, 52%, 25%",
        "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
        "--hsl-on-warning-container": "28, 100%, 87%",
        "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
        "--hsl-danger": "6, 100%, 84%",
        "--color-danger": "hsla(var(--hsl-danger), 1)",
        "--hsl-on-danger": "357, 100%, 21%",
        "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
        "--hsl-danger-container": "356, 100%, 29%",
        "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
        "--hsl-on-danger-container": "6, 100%, 84%",
        "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
        "--hsl-body": "350, 10%, 11%",
        "--color-body": "hsla(var(--hsl-body), 1)",
        "--hsl-text": "355, 24%, 90%",
        "--color-text": "hsla(var(--hsl-text), 1)",
        "--hsl-on-surface-variant": "354, 20%, 80%",
        "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
        "--hsl-outline": "350, 8%, 58%",
        "--color-outline": "hsla(var(--hsl-outline), 1)",
        "--hsl-inverse-surface": "355, 24%, 90%",
        "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)",
        "--chip-round-radius": "8px",
        "--field-decorator-line-border-radius": "50px",
        "--ripple-color": "hsla(var(--hsl-primary), 1)",
        "--color-profile-background": "hsla(var(--hsl-body), 1)",
        "--cell-padding": 0,
        "--card-background": "hsla(var(--hsl-body), 1)",
        "--bottom-navigation-background-color": "hsla(var(--hsl-body), 1)",
        "--tabs-indicator-inner-size": "50%",
        "--cell-font-size": "16px",
        "--cell-font-right": "100",
        "--result-background": "hsla(var(--hsl-body), 1)",
        "--back-top-button-size": "60px",
        "--tabs-background": "var(--color-body)",
}
}